### ISSUE TITLE
마이 페이지 테스트

### ISSUE THREAD

**Issue by shinsehantan** [woowacourse-teams/2021-drop-the-code#179]
- 렌더링 테스트
- 내가 학생이면 요청한 리뷰탭만 있는지 테스트
- 각 탭에 맞게 리뷰 리스트가 렌더링 되는지 테스트

**Comment by seojihwan** [comment]
기능 변경에 따라 테스트 내용 수정하였습니다.

- 사용자가 로그인 하지 않고 진입할경우 메인페이지로 리다이렉션
- 사용자가 로그인 되어 있는 경우 자신의 이름과 정보가 화면에 나타난다
  - 사용자가 리뷰어인 경우
    - 리뷰어 정보가 화면에 나타난다
    - 리뷰어 정보를 수정 할 수 있다
    - 리뷰어 정보를 삭제 할 수 있다
- 사용자가 로그인 되어 있는 경우 회원 탈퇴하면 메인 페이지로 이동한다
