### ISSUE TITLE
프론트 정적페이지 CI/CD 학습

### ISSUE THREAD

**Issue by seojihwan** [woowacourse-teams/2021-drop-the-code#19]

**Comment by seojihwan** [comment]
https://console.aws.amazon.com/cloudfront/home?# 문서에 따라서 구현 진행중

**Comment by shinsehantan** [comment]
`AWS CodePipeline`을 활용한 지속 배포 파이프라인 설정 문서
https://aws.amazon.com/ko/getting-started/hands-on/continuous-deployment-pipeline/

**Comment by shinsehantan** [comment]
https://docs.aws.amazon.com/codepipeline/latest/userguide/tutorials-simple-codecommit.html
