### ISSUE TITLE
전체 페이지 UI 개선 및 리팩터링

### ISSUE THREAD

**Issue by shinsehantan** [woowacourse-teams/2021-drop-the-code#195]
- 공통
  - 내용이 없을 때 텅빈 화면 제작
- 리뷰 상세 페이지
  - 안내문구 이미지 크기 줄이기
- 리뷰어 상세 페이지
  - 리뷰 목록 최신 순으로 정렬하면 좋을듯
  - 리뷰어 플로팅 박스에 `chip` `width` 조절하기
  - 리뷰어 플로팅 박스에 리뷰어라서 리뷰 요청하기 버튼이 없을 경우 해당 부분 다른 엘리먼트로 대체 혹은 빈공간 제거
  - 리뷰목록보기/접기 버튼 위아래 `margin` 주거나 일반 버튼 형식으로 대체
  - 리뷰어 상세 `content` 기본 `height`가 없어 내용이 별로 없을 때 어색함. 기본 `height` 지정하기
- 히스토리
  - 내가 요청한 리뷰/ 내가 맡은 리뷰 탭 UI 개선
  - `padding-bottom` 늘리기
- 토스트
  - 글자 길이에 맞춰서 늘어나도록 수정
  - 위아래 `margin` 줄이기 (지금 너무 뚱뚱)
  - `global style`의 `word-break: break-word`를 `word-break: break-all`로 바꿔서 단어 기준이 아니라 길이를 기준으로 `wrap` 되도록 하기
- 리팩터링
  - 요청 완료 후 적절한 페이지로 `redirect` 처리
- 컨펌
  - 리뷰 요청 시
  - 리뷰어 등록 시

**Comment by seojihwan** [comment]
마우스 hover시 카드들도 interaction이 발생하면 좋겟군요!
