### ISSUE TITLE
바벨 설정상, isDevelopment는 필요하지 않아보입니다.

### ISSUE THREAD

**Issue by Vallista** [woowacourse-teams/2021-drop-the-code#258]
https://github.com/woowacourse-teams/2021-drop-the-code/blob/c83ed1115eedd7f07f33ef216c5386b684561eee/frontend/babel.config.js#L3

- webpack 설정 상 NODE_ENV는 local, development, production 3가지로 나뉩니다.
- !production 아니면 production 만 되면 되지 않을까요?
- 그러므로 isDevelopment는 필요가 없어보입니다.

**Comment by Vallista** [comment]
지나가다 토픽에 뜨길래 남겨보았습니다.

**Comment by seojihwan** [comment]
안녕하세요 광휘님 오랜만입니다 ㅎㅎㅎ

좋은 comment 감사합니다~ 

webpack에서는 기본적으로 mode에 따라 process.env.NODE_ENV값이 적용됩니다. 

따라서 const isProduction = process.env.NODE_ENV === "production"의 값이 false일 경우 
process.env.NODE_ENV 값이 devlopment일 것으로 예상됩니다.

하지만 prcoess.env.NODE_ENV의 값이 development로 설정되는 것은 babel.config.js실행 이후인 것으로 확인됩니다.
webpack기본 설정에만 의존하는 경우 babel.config.js에서 process.env.NODE_ENV는 undefined가 됩니다.
이때 const isProduction은 false이고 !isProduction = true이기 때문에 webpack mode에 상관없이 development관련 설정들만 동작할 수 있습니다.

결론적으로 웹팩 기본설정과 babel.config.js에서만 놓고 보았을 때 process.env.NODE_ENV는 local | development | production임이 보장되지 않는다고 생각합니다. 요 부분에 대한 생각도 공유해주시면 감사하겠습니다~

**Comment by Vallista** [comment]
```js
const isDevelopment = process.env.NODE_ENV === "development";
const isProduction = process.env.NODE_ENV === "production";
```

"production" 인데 "production"이 아닌 경우가 나온다거나, "development" 인데 "development"가 아닌 경우가 나온다거나 인거죠? 그러면, 케이스는 다음과 같을 수 있습니다. "production" | "development" | "undefined" 로 둘 수 있겠어여. 위의 코드 예시상에서 isDevelopment를 사용하는 곳은 production이 아니면 되는것이고 (undefined일때도 development 동작이 적용되어도 문제 없어보입니다) isProduction을 사용하는 곳도 minify 적용 유무니, isProduction 일 때만 적용하면 됩니다. (undefined 일때 적용 안되어도 괜찮습니다.)

결국은, undefined 예외처리인데, 이 처리는 저렇게하나 이렇게하나 똑같습니다. 다만 제가 제시드린 부분이 코드 한 줄 더 적어보이네요. + 메모리 4바이트 아낌

**Comment by seojihwan** [comment]
말씀해주신 부분은 기존 의도대로 동작하는 좋은 방법이라고 생각합니다. 제시해주신 방법을 통해 분기를 주도록 변경하겠습니다.

여기에 더해 제 생각을 조금더 말씀드리겠습니다.

저는 process.env.NODE_ENV를 올바르게 설정하지 않은 경우  babel.config.js에서는 undefined가 될 수 있다는 점에 주목했습니다. undefined가 되더라도 isDevelopment가 true이므로 개발 모드에서는 올바르게 동작하여 인지를 못하다가 막상 배포 했을때에는 설정이 적용이안되고 있는 상황이 발생할 수 있습니다. 요 부분에 대한 대처를 하기위해 isDevelopment를 사용하여 개발환경에서 잘못된 세팅을 먼저 인지할 수 있도록 작성해보았는데 명확하지 않았네요.

따라서 개발자가 외부에서 process.env.NODE_ENV를 잘못 설정했을 때 알려주기위해 예외 처리를 추가하였습니다.
메모리는 더 사용하지만 process.env.NODE_ENV가 설정되지 않았을 경우를 대비할 수 있을거라 생각합니다.

**Comment by seojihwan** [comment]
테스트 수행결과 테스트 환경에서는 process.env.NODE_ENV가 test로 설정되어 react-refresh/babel 플러그인이 동작하게 되고 jest에서 에러가 발생했습니다.  production, development, test에 모두 대응해야 하기 때문에 isDevelopment또한 활용하여 3가지 이상의 환경에 대응 해야할 것 같습니다

**Comment by Vallista** [comment]
명확한 이유가 있으니 좋네요!
그런데 요러한 생각?이라던지 고민한 흔적이 코드에서는 크게 없어서..
코드상에 주석으로 달아주면 좋겠습니다!

**Comment by Vallista** [comment]
webpack, node등 기본 설정이 development로 되어있는것을 생각해보면,
development는 기본 상태라고 가정하고, 나머지 상태에 대한 예외를 진행하는게 더 좋지 않을까요?
webpack등에서도 기본 설정을 development로 두고 있으니, (또한 개발의 점유율이 높으므로)
이또한 코드 초기에 // 기본 설정은 development로 생각한다. 등을 적어두고,
다양한 환경에 대한 예외 (테스트, 프로덕션등)에 대해 대응하는 코드를 짜는게 조금 더 명확하지 않을지 의견 제시드립니다!

**Comment by seojihwan** [comment]
말씀해주신 것처럼 코드만 봐서는 의도를 파악하기 어렵다고 생각합니다! 이부분은 주석을 다는것이 더 명확한 것에 동의합니다.
하지만... webpack node등 기본 설정이 development라고 해주신 부분은 잘 이해가 가지 않습니다.  
webpack의 mode는 default가 production인 것으로 알고 있습니다! 
또한 기본 설정을 development로 가정한다면 부정연산자를 활용해야하고 조건도 더 복잡해져 가독성이 떨어진다고 생각합니다.

예를들어 react-refresh/babel 플러그인은 test와 production을 제외한 development에서 동작해야하므로
```js
[!isTest && !isProduction && "react-refresh/babel"].filter(Boolean)
```
와 같은 코드가 될 것입니다.

```js
[isDevelopment && "react-refresh/babel"].filter(Boolean)
```
아래의 코드가 더 좋다고 생각하는데 이부분에 대한 생각도 공유해주시면 감사하겠습니다!!🤔

**Comment by Vallista** [comment]
아하! 제가 잘못 알고 있었군요! development가 디폴트인줄 알았네요!
코드가 부정연산자가 먼저 들어간다면 가독성이 전체적으로 안좋아지므로 지환님 말씀대로 development 상태를 따로 가지고 있는게 더 가볍긴 하겠네요.. 

어디 쫌 괜찮은 사례가 없을까요? 이러한 상태들을 관리하기위해 저는 NODE_ENV를 안쓰고, APP_ENV라는 상태를 전역으로 별도로 구성해서 CLI로 자동적으로 다양한 환경이 맞물리도록 내부로직이 동작되도록 하고 있어요. 지금 당장은 그리 중요한 부분은 아니겠지만 추후 복잡해지면 is~~ 형태의 변수들이 선형적으로 늘어날테니 걱정이 되네요

**Comment by seojihwan** [comment]
말씀해주신 방법은 여러 환경들을 커스텀하게 관리해주신다는걸로 이해했습니다!
관리할 환경이 늘어난다면 일일이 대응 하는 것보다 변수의 숫자는 줄일 수 있겠네요~
하지만 각 환경마다 설정이 모두 고유하다면.. 변수의 선형적 증가는 불가피해보입니다. 또는 공통 설정만 분리하고, 서로 다른 설정은 별도의 파일로 만들어서 공통 설정을 가져다 쓰는 방법도 있다고 생각합니다~
아직 많은 환경을 경험해 보지는 않았지만 좋은 고민거리를 주셔서 감사합니다!
