### ISSUE TITLE
모든 스타일 관련 상수를 테마로 관리

### ISSUE THREAD

**Issue by seojihwan** [woowacourse-teams/2021-drop-the-code#30]

**Comment by shinsehantan** [comment]
box-shadow는 UI에 따라 변화가 많을 수 있어 테마 속성에 포함하는 것은 적합하지 않다고 생각하여 제외

**Comment by seojihwan** [comment]
일관성을 유지하는 점은 관련없지만 box-shadow를 테마로 관리해주면 더 효율적으로 관리할 수 있지 않을까요??

```
boxShadow: {
  header: '0 0 10 rgb(0 , 0, 0 , 0.1)',
  card: '0 0 20 rgb(0 , 0, 0 , 0.2)', 
}
```
추가적으로 사용되는 font size, z-index 등도 테마로 관리될 수 있을것 같아요
