### ISSUE TITLE
성능 테스트 시나리오

### ISSUE THREAD

**Issue by jh8579** [woowacourse-teams/2021-drop-the-code#355]
#### web-server
* ip - 13.209.3.143
* port - 80
#### was
* ip - 3.36.203.61
* port - 8080

### 인프라
* web server + was + replicated db
* was + statndalone db
* was + replicated db

### 시나리오
(수동으로 로그인 token)

* 로그인 - GET/login/oauth

* 언어 기술 목록 조회 -GET/languages

* 리뷰어 목록 조회 -GET/teachers?language=java
* 리뷰어 단일 조회 - GET/teachers/1

* 내가 받은 리뷰 목록 조회-token
* 내가 리뷰한 리뷰 목록 조회
* 리뷰 상세 조회
* 리뷰 수정

### DB Write
* access token 갱신
* 로그아웃 - refresh token

* 리뷰어 등록
* 리뷰어 수정- PUT/teachers/me - with token
* 리뷰어 삭제

* 리뷰 생성- POST/reviews - with token
* 리뷰 상태 업데이트 4개

* feedback

**Comment by hsik0225** [comment]
## 설정
- 부하테스트 도구 - JMeter
- 데이터 개수 : Member 기준 15만개

## 성능 목표 기준
### ResponseTime - 150ms
목표 Latency를 100으로 정했다.
JMeter는 ResponseTime의 통계만을 확인할 수 있기 때문에, ResponseTime을 기준으로 재설정했다.

ResponseTime = Latency + 전체 응답을 받는데 까지 걸린 시간이기 때문에, 
전체 응답을 받는데까지 걸린 시간을 최대 50ms로 가정하여 ResponseTime을 새로 목표 설정했다.

## JMeter 실행 방법
- [JMeter 설치 및 실행 방법](https://github.com/woowacourse-teams/2021-drop-the-code/wiki/JMeter-%EC%84%A4%EC%B9%98-%EB%B0%8F-%EC%8B%A4%ED%96%89-%EB%B0%A9%EB%B2%95)


## 성능 테스트 결과
- [대시보드](http://3.36.203.61/)

<details>
<summary>이미지 모음</summary>
<div markdown="4">
<br/>

- [성능 튜닝 전 - WAS](https://github.com/woowacourse-teams/2021-drop-the-code/wiki/%EC%84%B1%EB%8A%A5-%ED%8A%9C%EB%8B%9D-%EC%A0%84---WAS)

</div>
</details>
