### ISSUE TITLE
[QA] 로그인 후 access token 자동 만료

### ISSUE THREAD

**Issue by KJunseo** [woowacourse-teams/2021-drop-the-code#376]
### 현상
로그인 후 access token이 생겼다가 자동으로 사라짐

### 재현 스텝
로그인 

### 스크린샷
![access token 자동만료](https://user-images.githubusercontent.com/45876793/139051901-33b66842-b992-43e7-b777-30a6fb38479a.gif)

**Comment by kixtaxwax** [comment]
safari 동일 증상 발생

**Comment by hsik0225** [comment]
### WAS 실행 시 maximum-pool-size 설정을 안넣어줬기 때문에 발생했던 오류입니다.
maximum-pool-size 설정을 안넣어줬기 때문에 poolsize가 0으로 설정된채로 WAS가 띄어졌고, 
DB는 poolsize가 0이기 때문에 커넥션을 연결할 수가 없어서 에러가 발생했습니다.
shell script에 `Ddatasource.maximum-pool-size=20` 을 추가하여 해결했습니다.
