### ISSUE TITLE
[QA] access token은 살아있고 refresh token만 삭제하는 경우 로그아웃 되는 문제

### ISSUE THREAD

**Issue by KJunseo** [woowacourse-teams/2021-drop-the-code#379]
### 현상
access token은 살아있고 refresh token만 삭제하는 경우 로그아웃 되는 문제

### 재현 스텝
로그인 - refresh token 삭제 - 새로고침 - 로그아웃됨.

### 예상되는 원인
로그인 여부 판별을 access token 뿐만 아니라 refresh token 과도 같이 확인하나?

### 스크린샷
<img width="1440" alt="스크린샷 2021-10-27 오후 8 13 06" src="https://user-images.githubusercontent.com/45876793/139055106-20a1b10e-8b5e-47ee-95f5-1e9daf00a753.png">

**Comment by shinsehantan** [comment]
- 개발자도구를 열어서 refresh token을 삭제하는 경우는 정상적인 접근이 아니기에 로그아웃 처리를 하여도 무방할 것 같습니다. 이슈 클로즈하겠습니다.
