### ISSUE TITLE
[QA] 리뷰어 정보 수정시 언어 기술 선택하지 않고 수정버튼 누를 시

### ISSUE THREAD

**Issue by KJunseo** [woowacourse-teams/2021-drop-the-code#381]
### 현상
리뷰어 정보 수정시 언어 기술 선택하지 않고 수정버튼 누를 시 기존의 타이틀과 경력이 빈 값으로 변함

### 재현 스텝
로그인 - 마이페이지 - 리뷰어 정보 수정 - 언어/기술 선택없이 정보 수정 - 타이틀, 경력 빈값으로 변함

### 예상되는 원인
소개는 남아있는 걸로 봐서 구현이 다르게 되어있는 듯?

### 스크린샷
<img width="1440" alt="스크린샷 2021-10-27 오후 8 15 18" src="https://user-images.githubusercontent.com/45876793/139055468-96f9fd95-bd67-41ef-baab-a98a161c98a5.png">

**Comment by shinsehantan** [comment]
리뷰 수정 실패 시, 
타이틀, 경력, 소개 입력란을 모두 빈값으로 초기화하는 방식을 사용하기로 하였습니다. 
모달창을 닫고 다시 수정버튼을 누르면 기존 값을 다시 확인할 수 있습니다.
이슈 클로즈하겠습니다.
