### ISSUE TITLE
[QA] 리뷰어 정보 수정에서 유효성 검사 체크 미출력

### ISSUE THREAD

**Issue by hsik0225** [woowacourse-teams/2021-drop-the-code#383]
현상: 사파리 - 유효성 검사 체크 미출력
재현 스텝: 리뷰어 정보 수정에서 숫자가 아닌 다른 문자 입력
스크린샷:
![스크린샷 2021-10-27 오후 8 27 07](https://user-images.githubusercontent.com/56301069/139057049-8d7ee233-3245-41d8-844c-ffcc0012899f.png)

**Comment by shinsehantan** [comment]
- 숫자 외 유효하지 않은 글자 입력 시 제출은 불가하므로 반영 우선순위에서 배제하도록 하겠습니다. 이슈 클로즈하겠습니다.
