### ISSUE TITLE
[QA] 사파리에서 의도하지 않은 줄바꿈 

### ISSUE THREAD

**Issue by hsik0225** [woowacourse-teams/2021-drop-the-code#389]
현상: 사파리에서 의도하지 않은 줄바꿈 
재현 스텝: 사파리로 마이페이지, 리뷰 상세 접속
스크린샷:

![스크린샷 2021-10-27 오후 8 59 47](https://user-images.githubusercontent.com/56301069/139061855-88ab3100-f4ff-4542-b64b-c78cd510cbe4.png)
![스크린샷 2021-10-27 오후 9 00 01](https://user-images.githubusercontent.com/56301069/139061860-de36cb8d-8849-44ab-b9d1-ef6cb6a80b97.png)

**Comment by shinsehantan** [comment]
- 등록한 리뷰어 정보에서 '본문' 글자가 아래로 내려오는 부분은 수정 완료하였습니다.
- 리뷰 상세의 경우 사파리 브라우저에서 css의 'flex' 속성이 제대로 동작하지 않아서 문제가 발생한 것으로 추정되는데, 현시점에 사파리 크로스 브라우징을 위해 flex를 전부 걷어내는 것은 어렵다고 판단되어 본 이슈 클로즈 하겠습니다.
