### ISSUE TITLE
메인 페이지 리팩토링

### ISSUE THREAD

**Issue by seojihwan** [woowacourse-teams/2021-drop-the-code#40]
커스텀 훅으로 중복 로직 제거 및 선언적으로 코드 수정하기

**Comment by shinsehantan** [comment]
- string props 중괄호로 넘기는거 없애기

**Comment by shinsehantan** [comment]
- 더보기 버튼은 리뷰어 리스트 총 개수가 10개 이상일 때만 조건부 렌더링
