### ISSUE TITLE
api 요청 로직 작성

### ISSUE THREAD

**Issue by seojihwan** [woowacourse-teams/2021-drop-the-code#42]
# 구현사항
- fetch, axios 및 api관련 서드파티 라이브러리 중 선택하여 api 로직 작성하기

## 요구조건
- fetch 및 라이브러리 선택에 대한 명확한 이유가 존재하야한다.
- 에러핸들링과 타입정의가 명확해야한다.

**Comment by seojihwan** [comment]
axios에는 default 세팅, 응답을 공통적으로 처리할 수 있는 메서드를 제공하고 있음, 또한 업로드시 진행상황을 fetch에서는 확인할 수 없음

fetch를 이용해 직접 추상화 로직을 작성하는 것보다는 axios의 메서드를 사용하는 것이 협업할 때 적절하다고 판단함

**Comment by shinsehantan** [comment]
axios는 사이트 간 요청 위조(XSRF) 보호를 위한 클라이언트 사이드를 지원하여 보안 측면에서 fetch보다 우수하다고 판단함.
