### ISSUE TITLE
명도 대비 4.5:1 이하 컴포넌트 색상 변경 필요

### ISSUE THREAD

**Issue by shinsehantan** [woowacourse-teams/2021-drop-the-code#48]
<img width="946" alt="스크린샷 2021-07-14 오전 11 17 15" src="https://user-images.githubusercontent.com/67591151/125550795-31f7fdf0-bd00-4545-b543-10981d452e10.png">

- WAVE 웹 접근성 검사 결과 부적합
- 명도 대비 4.5:1 이상이 되도록  배경 색상 혹은 텍스트 색상 변경 필요

**Comment by seojihwan** [comment]
오... 색상 갈아 엎어야 겟네요!
