### ISSUE TITLE
UI 개선 

### ISSUE THREAD

**Issue by shinsehantan** [woowacourse-teams/2021-drop-the-code#64]

**Comment by seojihwan** [comment]
리뷰어 목록을 조회했을 떄 스크롤이 생기면서 헤더가 움직이는 현상이 윈도우에서 나타남

**Comment by shinsehantan** [comment]
누르면 최상단으로 이동하는 `top` 플로팅 버튼 구현하는 것도 좋을 것 같습니다.

**Comment by shinsehantan** [comment]
데모 이후 크루들의 피드백이 있었습니다.
- 리뷰어 카드 사이 마진 늘리기
- 리뷰어 카드 호버 시 효과 주기
