### ISSUE TITLE
테마 리팩터링

### ISSUE THREAD

**Issue by seojihwan** [woowacourse-teams/2021-drop-the-code#74]
# 테마 디렉토리 구조 변경 제안
테마의 폴더 위치를 src/theme로 두는 것은 어떨까요? (현재 src/utils/constants/theme.ts)

현재  components와 common  크게 2가지로 테마가 이루어져있는데
각각 src/theme/components, src/theme/common 으로 옮기고, theme/theme.ts에서 합치면 더 좋을것 같네요 

의견이 궁금합니다 @shinsehantan

**Comment by shinsehantan** [comment]
타입도 비슷하게 나누어 관리하고 있으니 변경해도 좋을 것 같습니다 :)

**Comment by shinsehantan** [comment]
- 버튼 테마로 disabled 색상을 추가적으로 관리한다.
