### ISSUE TITLE
Logback으로 Error 로그, Info 로그 남기기

### ISSUE THREAD

**Issue by jh8579** [woowacourse-teams/2021-drop-the-code#95]

**Comment by hsik0225** [comment]
### Query 문은 Log Level을 지정못하지 않나?
그렇다면 Application Log에 남기는 게 맞는 것일까?

**Comment by hsik0225** [comment]
- crontab으로 일정 기간이 지난 로그 삭제

**Comment by hsik0225** [comment]
# 로그
배포 시 남길 로그 파일
- error_log (stacktrace)
- sql_log
- application_log
- access_log
- build_log
